apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-clientes-vol
  # # namespace: postgres
  labels:
    app: postgres-clientes-vol
spec:
  storageClassName: csi-hostpath-sc
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi