apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-clientes-deployment
  # namespace: postgres
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: postgres-clientes
  template:
    metadata:
      labels:
        app: postgres-clientes
    spec:
      containers:
        - name: postgres-clientes-container
          image: postgres
          envFrom:
            - configMapRef:
                name: db-deployment-clientes-configmap
            - secretRef:
                name:  postgres-clientes-secrets
          ports:
            - containerPort: 5432
          


