apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-clientes-deployment
  # namespace: challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: challenge-clientes
  template:
    metadata:
      labels:
        app: challenge-clientes
    spec:
      # restartPolicy: Always 
      containers:
        - name: challenge-clientes-container
          image: encortondo/fiap-tech-challenge-clientes
          ports:
            - containerPort: 8081  
          command: ["npm", "run", "start"]
          envFrom:
            - configMapRef:
                name: deployment-clientes-configmap
            - secretRef:
                name:  challenge-clientes-secrets

