apiVersion: v1
kind: Service
metadata:
  name: postgres-clientes-service
  # namespace: postgres
spec:
  selector:
    app: postgres-clientes
  ports:
    - protocol: TCP
      port: 5432  
      targetPort: 5432
  
